server:
  port: 5000

spring:
  application:
    name: product-similarity
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full

# Logging básico
logging:
  level:
    root: INFO
    com.inditex: DEBUG
    org.springframework.cloud.openfeign: DEBUG
  structured:
    format:
      console: logstash     # o ecs / gelf
    arguments: true         # (opcional) añade key/values de logs como JSON
# Configuración de Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      product-api:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      product-api:
        maxAttempts: 3
        waitDuration: 500ms
  timelimiter:
    instances:
      product-api:
        timeoutDuration: 2s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
environment:
  OTEL_SERVICE_NAME: product-similarity-api
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  OTEL_METRICS_EXPORTER: none