{
 "title": "Product Similarity — Observability",
 "tags": [
  "spring-boot",
  "micrometer",
  "resilience4j"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "RPS (1m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Errores 5xx (5m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "p95 Latencia (ms)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000*histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Latencia p95/p99 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "1000*histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "1000*histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "RPS por endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m])) by (uri,method,status)",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Circuit breaker OPEN",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"open\"})",
     "legendFormat": "open"
    }
   ]
  },
  {
   "title": "Estado circuit breaker",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{name=\"product-api\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "JVM Heap usado (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})/1024/1024",
     "legendFormat": "heap used"
    }
   ]
  },
  {
   "title": "CPU proceso",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "proc cpu" }
   ]
  }
 ]
}